config/routes.rb
Picture::Application.routes.draw do
  resources :uploads

  resources :istocks

  resources :photos
  
  resources :tags
  
  resources :uploads
  

  root :to => "home#index"
  
  match "tags" => "tags#index"
  
  
  
  
  

end

app/models/istock.rb
class Istock < ActiveRecord::Base
end

app/controllers/istocks_controller.rb
class IstocksController < ApplicationController
  
  require "xmlrpc/client" 
  
  def index
    

      #find photo
      @photo = Photo.find(params[:id])
      # get photo file name
      image_file_name = @photo.image_file_name
      #pull out image_file_name_number
      

      doc = @photo.get_tags_from_istock
       render :text => doc  
  end
 end   

app/helpers/istocks_helper.rb
module IstocksHelper
end

app/views/istocks/_form.html.erb
<%= form_for(@istock) do |f| %>
  <% if @istock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@istock.errors.count, "error") %> prohibited this istock from being saved:</h2>

      <ul>
      <% @istock.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/istocks/edit.html.erb
<h1>Editing istock</h1>

<%= render 'form' %>

<%= link_to 'Show', @istock %> |
<%= link_to 'Back', istocks_path %>

app/views/istocks/new.html.erb
<h1>New istock</h1>

<%= render 'form' %>

<%= link_to 'Back', istocks_path %>

app/views/istocks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_istock_path(@istock) %> |
<%= link_to 'Back', istocks_path %>

app/views/istocks/xmlrpc.html.erb
<%= @info %>