config/routes.rb
Picture::Application.routes.draw do
  resources :uploads

  resources :istocks

  resources :photos
  
  resources :tags
  
  resources :uploads
  

  root :to => "home#index"
  
  match "tags" => "tags#index"
  
  
  
  
  

end

app/models/photo.rb
require "xmlrpc/client" 

class Photo < ActiveRecord::Base
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  attr_writer :tag_list, :tags, :taggings, :tag_id, :taggable_id
  
  #before_save :add_istock_tags
  
  searchable do
    text :name
    text :filetype
    text :tags   
  end
  
  def filetype
    image_content_type
  end
  
  
  def add_istock_tags
    tags = self.get_tags_from_istock
    self.tags = tags
  end
  
 # Find the number of tags on each photo for tag cloud
 #Photo.tag_counts_on(:tags)
 
  
 # def self.search(search)
 #   if search
 #     find(:all, :name.matches => ["%#{search}%"])
 #   else
 #     find(:all)
 #   end
 # end

  
  def get_tags_from_istock

  #Trying to not pass a "0" string to the parameters block because it will fail
  # if (self.istock_number == "0")
  # 
  #   # we dont have information about the istock #
  #    
  # else
  #   
  #   # we have information about the istock #
  #   
  # end
  # 
    
    
    #----- Check to see if this has an iStock Number to look for tags. This should definitely be tweaked because some of the file names are pulling down the wrong tags---#
  
      
    #----------Make an object to represent the XML-RPC server.---------#
    @server = XMLRPC::Client.new2("http://api.istockphoto.com/webservices/xmlrpc")
  
    #--------- Parameters passed to istock when server called--------#
  
    
    parameters = {:apiKey=>"bfe63c38e18bcf3c715a52f6", :fileID => self.istock_number}
  
    #---------- Call the remote server and get our result------------#
    result = @server.call("istockphoto.image.getInfo", parameters)
    
      #---- should add rescue if the photo doesn't have istock number = invalid parameter --#

  
    #--------------Output raw XML--------------------------------#
    #render :text => result, :content_type => 'text/xml'
    #@keywords = REXML::Document.new result
    
    #------ split up the tags------#
    doc = Nokogiri::XML(result)
    keywords = doc.xpath('//keywordList').text.split(',')
    keywords
    #@keywords = doc.xpath('//keywordList').text
    #keywords.inspect
  end

  # What I am doing here is trying to see if a photo doesn't have an istock name, allowing it to be saved.  But, I'm passing it bad tags, so this needs to be fixed.
  
  def istock_number
       y = image_file_name.scan(/\d{4,}/)
       if (y == nil || y == 0)
         x = "3967984"
       #image_file_name.scan(/\d{4,}/).first.to_i.to_s
     else
      x = image_file_name.scan(/\d{4,}/).first.to_i.to_s
     end
     
     puts x
     
      return x
  end
  
  def tag
    @tags = Tag.all
  end
  
  # Taggable images
  acts_as_taggable_on :tags
  

  #---------Paperclip Validations -----------#
  # validates_attachment_presence, :images
  # validates_attachement_content_type :images, :content_type => 'image/jpeg', 'application/postscript'
  
  #-------- Paperclip & Formatting -----------#
  has_attached_file :image, :styles => { :thumb => ["90x90#", :jpg],
                                         :small => ["300x300^", :jpg],
                                         :medium => ["380>x380>", :jpg]}
                    #Add this to get the file to download automatically
                    
                    
                    ##--------Configure url where Paperclip accesses photo -----------#
                    #:url => "/:attachment/:id/:style/:basename.:extension",
                    ##--------Configures path where rails stores uploaded files---#
                    #:path => ":rails_root/public/:attachment/:id/:style/:basename.:extension"
                    
                    ##---------Consider adding in validations like this---------#
                    #validates_attachment_presence :mp3
                     # validates_attachment_content_type :mp3, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ]
                     # validates_attachment_size :mp3, :less_than => 20.megabytes
  
  attr_protected :image_file_name, :image_content_type, :image_file_size
                  
                  
  
    
  ### Search photos by keywords ###
  #def self.search(search)
    
    #if search
    #  @photos = Photo.where("%#{params[:search]}%")
  #  else
   #   find.all(:order => "created_at desc")
   # end  
  # end
  
  
                       
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.xml
 
 
   def index
  #   @photos = if params[:q].blank?
  #     Photo.all(:order => "created_at desc").paginate(:page => params[:page], :per_page => 100)
  #    else
  #      Product.solr_search do |s|
  #        s.keywords params [:q]
  #      end
  #    end
  #  end
     
     
     if params[:search]
       @search = Photo.search do
          fulltext params[:search]
        end
       @photos = @search.results.paginate(:page => params[:page], :per_page => 100)
    else
       @photos = Photo.all(:order => "created_at desc").paginate(:page => params[:page], :per_page => 100)
    end
   end
 
  #def index
  #  @photos = Photo.all #search(params[:search])
  #end

  def show
    @photo = Photo.find(params[:id])
     
  end

  def new
    @photo = Photo.new
    

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

 
  def create
    @photo = Photo.new(params[:photo])
    
    respond_to do |format|
      if @photo.save
        format.html { redirect_to(@photo, :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(photos_url) }
      format.xml  { head :ok }
    end
  end
  
  #---------- iStock Controller --------------#
  
  require "xmlrpc/client" 

   # Tag Cloud
   def tag_cloud
       @tags = Photo.tag_counts_on(:tags)
    end
   
  #def download
  #  @photo = Photo.find(params[:id])
  #  send_file '/images/@photo./original/iStock_000000058748Small.jpg'
  #
  # end
   
    
end

app/helpers/photos_helper.rb
module PhotosHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo, :html => { :multipart => true }) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 	<div class="actions">
		<%= f.label :image %><br />
    	<%= f.file_field :image %>
  	</div>
  	<div class="field">
    	<%= f.label :name %><br />
    	<%= f.text_field :name %>
  	</div>
  	<div class="field">
		<%= f.label :Tags %><br />
		<%= f.text_field :tag_list %>
  	</div>
  	<div class="actions">
    	<%= f.submit %>
  	</div>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit photo</h1>
<%= image_tag @photo.image.url(:small) %>
<%= render 'form' %>
<br />
<br />
<%= @photo.get_tags_from_istock %>
<br />
<br />
<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="browse_images">
	
	<!--<h1>Thinktiv Image Assets</h1>-->
	<%# @tags.each do |tag| %>
	<%#= link_to tag.name.capitalize, tag_path(tag) %>
	<%# end %>
	
	<div class="imagePreview">
		<ul class="gallery">
			<% @photos.each do |photo| %>
			<!--<li><%#= photo.tag_list %></li>-->
			
			<!--Use this to click on the photo and edit a photo-->
			<!--<li><a><%#=link_to(image_tag(photo.image.url(:thumb)), edit_photo_path(photo)) %></a></li>-->
		<!--<li><%#= photo.tag_list %></li>-->
			<li>
				<p id="thumbnail">
					<a class= "preview" href="<%= image_path(photo.image.url(:small)) %>" title="<%= photo.name %>"> <%= image_tag(photo.image.url(:thumb)) %></a>
				</p>
				<p id="download">
					<a class="original" href="<%= photo.image.url(:original, false) %>"> Download</a>  <%= link_to 'Edit', edit_photo_path(photo) %>
				</p>
			
			</li>


			<!--Download a file to attachment
			<li><%#= link_to "Download", download %></li>-->

			<!--Download a file in the browser-->
			<!--<li id="text"><%#= link_to "Download", photo.image.url(:original, false) %></li>-->
			
			
			<% end %>
		</ul><!---gallery of images-->
		<span></span>
		<%= will_paginate @photos %>
	</div>
	
	
</div>

<%#= link_to 'Destroy', photo,
			:confirm => 'Are you sure?',
			:method => :delete %>
			
			

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<!--If there is an image, I want to display it in thumbnail form-->
<% if @photo.image? %>
	<%= image_tag @photo.image.url(:small) %>
<% end %>

<p>
  <b>Name:</b>
  <%= @photo.name %>
</p>
<p>
  <b>Tags:</b>
  <%= @photo.tag_list %>
</p>

<p>
	<%= @photo.istock_number %>
</p>

<p><%= @photo.get_tags_from_istock %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>